/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'form-expense-budget-draft': RouteRecordInfo<'form-expense-budget-draft', '/form/expense-budget-draft', Record<never, never>, Record<never, never>>,
    'form-expense-budget-draft_id': RouteRecordInfo<'form-expense-budget-draft_id', '/form/expense-budget-draft/:_id', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'form-expense-budget-draft_id-edit': RouteRecordInfo<'form-expense-budget-draft_id-edit', '/form/expense-budget-draft/:_id/edit', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'form-expense-budget-draft-create': RouteRecordInfo<'form-expense-budget-draft-create', '/form/expense-budget-draft/create', Record<never, never>, Record<never, never>>,
    'form-government-personnel-expense': RouteRecordInfo<'form-government-personnel-expense', '/form/government-personnel-expense', Record<never, never>, Record<never, never>>,
    'form-government-personnel-expense_id': RouteRecordInfo<'form-government-personnel-expense_id', '/form/government-personnel-expense/:_id', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'form-government-personnel-expense_id-edit': RouteRecordInfo<'form-government-personnel-expense_id-edit', '/form/government-personnel-expense/:_id/edit', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'form-government-personnel-expense-create': RouteRecordInfo<'form-government-personnel-expense-create', '/form/government-personnel-expense/create', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'master-data-activities': RouteRecordInfo<'master-data-activities', '/master-data/activities', Record<never, never>, Record<never, never>>,
    'master-data-activities_id': RouteRecordInfo<'master-data-activities_id', '/master-data/activities/:_id', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-activities_id-edit': RouteRecordInfo<'master-data-activities_id-edit', '/master-data/activities/:_id/edit', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-activities-create': RouteRecordInfo<'master-data-activities-create', '/master-data/activities/create', Record<never, never>, Record<never, never>>,
    'master-data-area-based': RouteRecordInfo<'master-data-area-based', '/master-data/area-based', Record<never, never>, Record<never, never>>,
    'master-data-area-based_id': RouteRecordInfo<'master-data-area-based_id', '/master-data/area-based/:_id', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-area-based_id-edit': RouteRecordInfo<'master-data-area-based_id-edit', '/master-data/area-based/:_id/edit', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-area-based-create': RouteRecordInfo<'master-data-area-based-create', '/master-data/area-based/create', Record<never, never>, Record<never, never>>,
    'master-data-budget-categories': RouteRecordInfo<'master-data-budget-categories', '/master-data/budget-categories', Record<never, never>, Record<never, never>>,
    'master-data-budget-categories_id': RouteRecordInfo<'master-data-budget-categories_id', '/master-data/budget-categories/:_id', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-budget-categories_id-edit': RouteRecordInfo<'master-data-budget-categories_id-edit', '/master-data/budget-categories/:_id/edit', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-budget-categories-create': RouteRecordInfo<'master-data-budget-categories-create', '/master-data/budget-categories/create', Record<never, never>, Record<never, never>>,
    'master-data-national-strategies': RouteRecordInfo<'master-data-national-strategies', '/master-data/national-strategies', Record<never, never>, Record<never, never>>,
    'master-data-national-strategies_id': RouteRecordInfo<'master-data-national-strategies_id', '/master-data/national-strategies/:_id', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-national-strategies_id-edit': RouteRecordInfo<'master-data-national-strategies_id-edit', '/master-data/national-strategies/:_id/edit', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-national-strategies-create': RouteRecordInfo<'master-data-national-strategies-create', '/master-data/national-strategies/create', Record<never, never>, Record<never, never>>,
    'master-data-organizations': RouteRecordInfo<'master-data-organizations', '/master-data/organizations', Record<never, never>, Record<never, never>>,
    'master-data-organizations_id': RouteRecordInfo<'master-data-organizations_id', '/master-data/organizations/:_id', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-organizations_id-edit': RouteRecordInfo<'master-data-organizations_id-edit', '/master-data/organizations/:_id/edit', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-organizations-create': RouteRecordInfo<'master-data-organizations-create', '/master-data/organizations/create', Record<never, never>, Record<never, never>>,
    'master-data-output-projects': RouteRecordInfo<'master-data-output-projects', '/master-data/output-projects', Record<never, never>, Record<never, never>>,
    'master-data-output-projects_id': RouteRecordInfo<'master-data-output-projects_id', '/master-data/output-projects/:_id', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-output-projects_id-edit': RouteRecordInfo<'master-data-output-projects_id-edit', '/master-data/output-projects/:_id/edit', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-output-projects-create': RouteRecordInfo<'master-data-output-projects-create', '/master-data/output-projects/create', Record<never, never>, Record<never, never>>,
    'master-data-plans': RouteRecordInfo<'master-data-plans', '/master-data/plans', Record<never, never>, Record<never, never>>,
    'master-data-plans_id': RouteRecordInfo<'master-data-plans_id', '/master-data/plans/:_id', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-plans_id-edit': RouteRecordInfo<'master-data-plans_id-edit', '/master-data/plans/:_id/edit', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-plans-create': RouteRecordInfo<'master-data-plans-create', '/master-data/plans/create', Record<never, never>, Record<never, never>>,
    'master-data-river-basins': RouteRecordInfo<'master-data-river-basins', '/master-data/river-basins', Record<never, never>, Record<never, never>>,
    'master-data-river-basins_id': RouteRecordInfo<'master-data-river-basins_id', '/master-data/river-basins/:_id', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-river-basins_id-edit': RouteRecordInfo<'master-data-river-basins_id-edit', '/master-data/river-basins/:_id/edit', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-river-basins-create': RouteRecordInfo<'master-data-river-basins-create', '/master-data/river-basins/create', Record<never, never>, Record<never, never>>,
    'master-data-royal-initiative-types': RouteRecordInfo<'master-data-royal-initiative-types', '/master-data/royal-initiative-types', Record<never, never>, Record<never, never>>,
    'master-data-royal-initiative-types_id': RouteRecordInfo<'master-data-royal-initiative-types_id', '/master-data/royal-initiative-types/:_id', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-royal-initiative-types_id-edit': RouteRecordInfo<'master-data-royal-initiative-types_id-edit', '/master-data/royal-initiative-types/:_id/edit', { _id: ParamValue<true> }, { _id: ParamValue<false> }>,
    'master-data-royal-initiative-types-create': RouteRecordInfo<'master-data-royal-initiative-types-create', '/master-data/royal-initiative-types/create', Record<never, never>, Record<never, never>>,
  }
}
